-- 코드를 입력하세요
SELECT BI.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES 
FROM BOOK_SALES BS
JOIN (
    SELECT BOOK_ID, CATEGORY, B.AUTHOR_ID, PRICE, AUTHOR_NAME
    FROM BOOK B
    JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
) BI
ON BS.BOOK_ID = BI.BOOK_ID
WHERE SALES_DATE>='2022-01-01' AND SALES_DATE<'2022-02-01'
GROUP BY BI.AUTHOR_ID, CATEGORY
ORDER BY BI.AUTHOR_ID, CATEGORY DESC