-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS, ROUND( COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)=2021), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE OS
JOIN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED)=2021) UI
ON OS.USER_ID = UI.USER_ID
GROUP BY YEAR, MONTH