-- 코드를 입력하세요
SELECT P.PRODUCT_ID, PRODUCT_NAME, P.PRICE*SUM(O.AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID