-- 코드를 입력하세요
SELECT F1.CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F1
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) F2
ON F1.CATEGORY = F2.CATEGORY
WHERE F1.CATEGORY IN ('과자', '국', '김치', '식용유') AND F1.PRICE = F2.MAX_PRICE
ORDER BY PRICE DESC